name: Run BOSH Start

on:
  workflow_dispatch: { }

jobs:
  bosh-start:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install BOSH CLI
        run: |
          wget -q https://github.com/cloudfoundry/bosh-cli/releases/download/v7.6.1/bosh-cli-7.6.1-linux-amd64
          chmod +x bosh-cli-7.6.1-linux-amd64
          sudo mv bosh-cli-7.6.1-linux-amd64 /usr/local/bin/bosh
          bosh -v
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3.0.0
        with:
          exportToken: true
          exportEnv: true
          method: jwt
          url: ${{ secrets.VAULT_ADDR }}
          role: cicd
          secrets: |
            kv/data/cicd/bosh environment | BOSH_ENVIRONMENT ;
            kv/data/cicd/bosh client | BOSH_CLIENT ;
            kv/data/cicd/bosh client_secret | BOSH_CLIENT_SECRET ;
            kv/data/cicd/bosh ca_cert | BOSH_CA_CERT ;   
            kv/data/cicd/bosh all_proxy | BOSH_ALL_PROXY ;  
            kv/data/cicd/bosh private_key | PRIVATE_KEY ;   
      - name: Set up BOSH environment variables
        run: |
          cat <<EOF > /tmp/private_key.pem
          ${PRIVATE_KEY}
          EOF
          chmod 600 /tmp/private_key.pem
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/config
          host *
            StrictHostKeyChecking no
          EOF
      - name: Run bosh deployments
        run: |
          bosh deployments --json | jq -r '.Tables[0].Rows[].name' > deployments.txt
      - name: Start cf
        run: |
          DEPLOYMENT_NAME=$(cat deployments.txt | grep -E '^cf-')
          bosh start -d ${DEPLOYMENT_NAME} -n
      - name: Start postgres
        run: |
          DEPLOYMENT_NAME=$(cat deployments.txt | grep -E '^postgres-')
          bosh start -d ${DEPLOYMENT_NAME} -n
      - name: Start p-healthwatch2
        run: |
          DEPLOYMENT_NAME=$(cat deployments.txt | grep -E '^p-healthwatch2' | grep -Ev '^p-healthwatch2-pas')
          bosh start -d ${DEPLOYMENT_NAME} -n
      - name: Start p-healthwatch2-pas-exporter
        run: |
          DEPLOYMENT_NAME=$(cat deployments.txt | grep -E '^p-healthwatch2-pas-exporter')
          bosh start -d ${DEPLOYMENT_NAME} -n
      - name: Revoke token
        if: always()
        run: |
          curl -X POST -s -H "X-Vault-Token: ${VAULT_TOKEN}" ${{ secrets.VAULT_ADDR }}/v1/auth/token/revoke-self || true
